# Read the Docs configuration file for Prismo
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/source directory with Sphinx
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
    post_install:
      # Install dependencies
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Python requirements
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Formats to build
formats:
  - pdf
  - epub

# Submodules
submodules:
  include: []
  recursive: false
